version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "data"
      POSTGRES_USER: "data_engineer"
      POSTGRES_PASSWORD: "data_engineer"
    ports:
      - "5432:5432"
    volumes:
      - ./persons.sql:/tmp/persons.sql